### ISSUE TITLE
Questions on the workflow of the middleware, and maybe suggestions

### ISSUE THREAD

**Issue by MFYDev** [magicpages/ghost-bunnycdn-middleware#1]
Hi Jannis,

I have a question, I just read the code in `index.ts`, although I did not learn typescript before but I think I can still understand a bit. 

Your code as long as got the `X-Cache-Invalidate` header and then you will purge the whole pull zone's cache right? This did not purge cache for a specific url, and by purging the whole zone cache, there will be a new perma-cache folder created in the storage, so seems like this code did not take care of the old perma-cache folder in your storage and it will still take space, you still have to manually delete those right?

Unlike my repo: https://github.com/MFYDev/Ghost-BunnyCDN-Cache-Clearer, the webhook in this way can automatically take care of auto deleting the old perma cache folder as well.

Am I understanding correctly? 

If I am right, does that mean maybe adding auto delete the perma-cache old folder will be more financially efficient?

**Comment by betschki** [comment]
Yes, that's a great point!

I am purging the entire cache, as the `X-Cache-Invalidate` header specifies `/*` to be purged.

But yes, will be a good addition to also delete the old perma-cache folders. Will look into this in the future – if you want to get into Typescript a bit, feel free to add a PR as well 😄

**Comment by betschki** [comment]
@MFYDev just merged some changes that implements your suggestion – already live on my own blog jannis.io. Rather than using SFTP, like in your implementation, I decided to use the REST API to reduce dependencies. Works like a charm! Thanks for the suggestion :)

**Comment by MFYDev** [comment]
@betschki Perfect! The reason why I am using SFTP was tricky, it was mainly because the first moment when I was trying to use the api to delete folders it was not working well for some reasons, so I just sticked with the sftp, but you are right, I should refactor my code as well to make it use the rest api to reduce dependencies thank you!

**Comment by MFYDev** [comment]
@betschki Just want to make sure cause I am using Standard Storage instead of the edge storage on Bunny, so in this case you can use the edge storage api, but I tried multiple times for me myself, edge storage delete api seems like is not working for my standard storage

**Comment by betschki** [comment]
@MFYDev whatever tool does the job, is the best tool – I think both are good options. In my API-driven world, the REST API just made more sense 😄

**Comment by MFYDev** [comment]
@betschki you are right, I actually just rewrote the whole code, make it can be deployed on the cloudflare worker
